### ISSUE TITLE
Obsidian Gallery lists Version 1.0.3 and refuses to install; 1.0.2 latest release in this repo

### ISSUE THREAD

**Issue by davejdyer** [ozdemir08/youtube-video-summarizer#13]
The title pretty much says it all. I noticed that an update was pending but failing in my Obisidian vault. I tried uninstalling the 1.0.2 version and reinstalling it from the gallery, but it still failed. That's when I realized this repo hasn't published a 1.0.3. So now, the plugin can't be installed from the gallery at all.

I realize that I could manually install it, but I'll wait until this is resolved. 

Hope this helps. Thank you!

**Comment by joethei** [comment]
Hi @ozdemir08, please fix this issue.

We will remove this plugin from the community plugins if this issue is not fixed within 30 days.
- The Obsidian team.

**Comment by ozdemir08** [comment]
Thanks @davejdyer for filing this. I reverted the version to 1.0.2 now. I also tried uninstalling/installing it on my laptop. This should be fixed now. Let me know if the issue persists for you.
